name: 'Action-To-Pushgateway'
description: 'Send prometehus metrics to pushgateway'
inputs:
  pushgateway:
    description: 'prometheus pushgateway address'
    required: true
  token:
    description: 'github token'
    required: true
  previousstate:
    description: 'The last step status'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
