name: 'Action-To-Pushgateway'
description: 'Send prometehus metrics to pushgateway'
inputs:
  pushgateway:
    description: 'prometheus pushgateway address'
    required: true
    default: 'http://127.0.0.1:9091'
runs:
  using: 'node12'
  main: 'dist/index.js'
