name: "hello-world-js"
on:
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  hello-world-js:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/hello-world-javascript-action@master
      with:
        who-to-greet: 'Mona the Octocat'
